[package]
name = "cgmemtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
clone3 = "0.2.3"
nix = "0.26.2"
tempfile = "3.5.0"
